#!/bin/sh

FILENAME=parseconfig.c

A=$(grep -n parse_config ${FILENAME} | awk -F : {'print $1'})
B=$(grep -n "*cfg;" ${FILENAME} | awk -F : {'print $1'})
A=$((A+1))
B=$((B-1))

sed -n "$A,$B p" ${FILENAME} | sed "$(grep define parseconfig.h | sed "s@#define @@g" | awk {'print $1" "$2'} | sed -r 's|(.*)\ (.*)|s@\\<\1\\>@\2@|g' |  tr "\n" ";" ) ; s|    ||g" | grep -v "^$"

